//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorLocalization() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditorLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert hyperlink.
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete {0}?.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A directory with this name was not found..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty Folder.
        /// </summary>
        internal static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select font family.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (inherited font).
        /// </summary>
        internal static string FontNameInherit {
            get {
                return ResourceManager.GetString("FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select font size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (inherited size).
        /// </summary>
        internal static string FontSizeInherit {
            get {
                return ResourceManager.GetString("FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select block type.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indent.
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert HTML.
        /// </summary>
        internal static string InsertHtml {
            get {
                return ResourceManager.GetString("InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert image.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert ordered list.
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert unordered list.
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file {0} is not valid. Supported file types are {1}..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center text.
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justify.
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Align text left.
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Align text right.
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open link in new window.
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange by:.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string OrderByName {
            get {
                return ResourceManager.GetString("OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string OrderBySize {
            get {
                return ResourceManager.GetString("OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outdent.
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A file with name {0} already exists in the current directory. Do you want to overwrite it?.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strikethrough.
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Styles.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tooltip.
        /// </summary>
        internal static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove hyperlink.
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web address.
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
    }
}
